/** The Worker's bindings, generated by `pnpm cf-typegen` from wrangler.jsonc plus the
 *  local env file. Aliased rather than re-declared: this name is what codegen's
 *  `contextType` resolves to, and there must be one description of the bindings. */
export type Env = WorkerEnv;
