/** The Worker's bindings, generated by `pnpm cf-typegen` from wrangler.jsonc plus the
 *  local env file, plus Yoga's request.
 *
 *  Yoga merges its initial context — request, params, waitUntil — into what resolvers
 *  receive, so `request` is there even though nothing in wrangler.jsonc puts it there.
 *  codegen's `contextType` points here, so naming it retypes every resolver at once.
 *
 *  `Partial<ExecutionContext>` for the same reason, one step less obviously: on a Worker
 *  Yoga is handed `env` and `ctx` and merges both, so `waitUntil` reaches a resolver too
 *  — and it is Partial because the tests call `worker.fetch` with two arguments. Leaving
 *  it out does not merely under-describe the context, it stops src/index.ts compiling:
 *  Yoga takes extra context as `Partial<Env>`, and TypeScript rejects an object type
 *  with no property in common with the target. */
export type Env = WorkerEnv & { request: Request } & Partial<ExecutionContext>;
